### ISSUE TITLE
complete the implementation of the password manager imp class

### ISSUE THREAD

**Issue by MuhammadAli251018** [MuhammadAli251018/Password-Manager-Desktop#1]
you should:
- [x] **Implement** the key encode function
- [x] **Implement** the key decode function
- [x] **Implement** the encryption function
- [x] **Implement** the decryption function

**Comment by MrOstricho** [comment]
encode & decode functions are pushed

**Comment by MrOstricho** [comment]
encryption and decryption are tested and pushed successfully
